### ISSUE TITLE
Odd Reading of Output When Using a Screenreader

### ISSUE THREAD

**Issue by hjozwiak** [LiquidityC/Blightmud#106]
**Describe the bug**
When playing MUDs with BlightMUD, the screenreading software reads older lines as newer ones come in, when it should be reading just the new lines that come in.
**To Reproduce**
Software in use: Orca screenreader, compiled from the git master branch
GNOME desktop 3.36
Arch Linux
When playing a MUD, try navigating around and observe that as you move, Orca will read older lines and eventually read the new lines that come in, though any input that comes in will also cause the screenreader to read older lines.
**What terminal are you using?**
gnome-terminal

**What mud were you playing?**
legendsofkallisti.com:4000
stickmud.com:7680
**Screenshots**

**Comment by LiquidityC** [comment]
Interesting. Little experience with screen readers. I'll take a look.

**Comment by LiquidityC** [comment]
Ok, I've had a look at this. As far as I can understand this is an artifact created by the fact that we use "raw mode" in the terminal when drawing blightmud to screen. Every new line causes a shift in the output and orca or gnome-terminal interprets this as "everything on screen is new data".

Sadly, I haven't found much information on how we could get around this without a massive re-write to the TUI or patching gnome-terminal in some way.

However, I did find a TTS library in rust which seemed to work rather nicely. I'd be willing to set up a task for this and get a "native" TTS functionality implemented in Blightmud. However, I don't use screen readers on a regular basis. It would be important to me that this was tested by someone with actual experience and demands on function. I don't just want to shove it in and assume that everything is fine.

The major upside of this that I can see is that we could allow TTS to be scriptable. Eg. You could gag lines to not be spoken to you through lua. You could gag the prompt, set triggers that tell you more vital information. Eg. "Your health is low" etc. Some muds have really long lines to tell you that someone entered the room. You could theoretically gag the TTS and make it tell you something shorter. This is just based on my assumptions in regards to how I think someone using a screen reader would play though.

So, If this sounds like something that'd be of interest I can set it up. Just get back to me and I'll set aside some time.

**Comment by hjozwiak** [comment]
> Ok, I've had a look at this. As far as I can understand this is an artifact created by the fact that we use "raw mode" in the terminal when drawing blightmud to screen. Every new line causes a shift in the output and orca or gnome-terminal interprets this as "everything on screen is new data". I think this is an Orca issue, I have tried it with several other terminal emulators with the same result. My friend and I tried it on a TTY screenreader which seems to work in the correct manner.
> 
> Sadly, I haven't found much information on how we could get around this without a massive re-write to the TUI or patching gnome-terminal in some way.
> I can reach out to the orca developer and see what they suggest.
> However, I did find a TTS library in rust which seemed to work rather nicely. I'd be willing to set up a task for this and get a "native" TTS functionality implemented in Blightmud. However, I don't use screen readers on a regular basis. It would be important to me that this was tested by someone with actual experience and demands on function. I don't just want to shove it in and assume that everything is fine.
> 
> The major upside of this that I can see is that we could allow TTS to be scriptable. Eg. You could gag lines to not be spoken to you through lua. You could gag the prompt, set triggers that tell you more vital information. Eg. "Your health is low" etc. Some muds have really long lines to tell you that someone entered the room. You could theoretically gag the TTS and make it tell you something shorter. This is just based on my assumptions in regards to how I think someone using a screen reader would play though.
> You are on the write track. Historically speaking, I used a utility called sox to generate tones for tracking health, mana, or stamina, which in turn allows us to drop the text prompt altogether. The other upshot is that on machines that don't have a screenreader installed, a person can play a MUD just by using BlightMUD.
> So, If this sounds like something that'd be of interest I can set it up. Just get back to me and I'll set aside some time.
It would certainly be of interest, especially when it comes to audio prompt generation. For inspiration or a bit of historical context, https://gitlab.com/hjozwiak/tintin-kallisti-pack is my most recent package.

**Comment by LiquidityC** [comment]
Closing this since it's nothing we can fix really. #110 will address the implementation of TTS
