### ISSUE TITLE
Support for TLS connections

### ISSUE THREAD

**Issue by LiquidityC** [LiquidityC/Blightmud#12]
Didn't really know this was a thing but someone asked for it.

**Comment by lisdude** [comment]
The test server I set up has a TLS port if you want to test this there: lisdude.com port 1138

**Comment by LiquidityC** [comment]
Just a quick bump. I've been looking into this on and off. The way connections work now and the way they'd need to work with TLS is a bit different. Hence I've had to ponder it a while longer. I think I have a solid design for how I want this to look now. Just need to find some time to fiddle with it. Updates will come.

**Comment by LiquidityC** [comment]
Ok @lisdude, I have some good news.

Please checkout the branch `mud_connection_impl` and test out TLS
using `/connect host port tls` eg. `/connect lisdude.com 1138 tls`.
This should also work with `/add_server tls lisdude.com 1138 tls`.

Also lua `blight:connect(host, port, tls) -- where tls = true or false` should work.

This *might* mess up your stored servers for the `master` and `dev` branch until I merge this.

I still need to update the documentation but the core functionality should be there. Please test away!

**Comment by lisdude** [comment]
Awesome! It seems to be working great so far. Thank you!

**Comment by LiquidityC** [comment]
You're welcome. This one took a lot of brainpower :thinking:
