### ISSUE TITLE
Support for plugins

### ISSUE THREAD

**Issue by LiquidityC** [LiquidityC/Blightmud#122]
With the current state of lua in Blightmud I think It's possible to setup a manner of plugin framework.

This task should act as a main task to track the overall solution.

This is how I think we can solve it:

- [ ] Setup a file in this repo that holds a list of plugins (json, ron or whatever fits). The data should be, **name**, **description** and **git repo link**. Place it under `/repo/plugins.<suffix>`
- [ ] Add functionality in blightmud to retrieve this file from the dev branch and parse it.
- [ ] Add functionality in blightmud to install/remove plugins stored in `~/.local/share/blightmud/plugins/<plugin>/`. Eg. `/plugin [un]install <name|git url>` and `/plugin list` (use a git crate for this and always fetch the master branch, we can stipulate these rules to plugin maintainers)
- [ ] Add functionality to update a plugin git repo if available
- [ ] Add functionality to load in plugins at boot (core mode). Plugins need to present a `main.lua` file in their root which loads and runs what's needed.

If someone wants to add their plugin to the internal list in blightmud they need to submit a PR to this repo with the information for the plugin added.

If you want to work on this then target the PR to the `plugin_impl` branch. If it doesn't exist yet then just speak up and we will add it.

**Comment by Xandaros** [comment]
I'd like to request also making it possible to directly giving a link to a git repo or a username/repo pair for GitHub repositories, as well.

**Comment by LiquidityC** [comment]
> I'd like to request also making it possible to directly giving a link to a git repo or a username/repo pair for GitHub repositories, as well.

@Xandaros Glad you brought your brains to the discussion! I have updated the task :wink:
