### ISSUE TITLE
Make it possible to bind keys using escape sequences

### ISSUE THREAD

**Issue by LiquidityC** [LiquidityC/Blightmud#128]
The crate we use for TUI (termion) has a limited number of key combinations which it will detect.
This makes binding on ctrl-up/down/left/right impossible.

However we can catch the actual byte sequence when a key combination is recognized.

So we could add a possibility to bind keys based on that.

eg.
```lua
-- Bind ctrl-up
blight:bind_sequence("\x1b[1;5A", function ()
    -- Do stuff
end)
```

**Comment by DanB288** [comment]
Hey @LiquidityC !!, I'd like to work on this issue. Can you assign it to me?😉

**Comment by LiquidityC** [comment]
I tend to not assign issues until there's a PR. But go ahead. There's mostly me writing code here so I'll leave this one for you 😉
