### ISSUE TITLE
Option to echo all GMCP messages

### ISSUE THREAD

**Issue by Xandaros** [LiquidityC/Blightmud#135]
There used to be an option to output all incoming GMCP messages. This was removed when the GMCP implementation was moved from rust to Lua.

Perhaps simply offering an option to register a handler that receives all GMCP messages, regardless of module, might be good here. Users can then echo, log, or do whatever else they want to do with those messages.

**Comment by LiquidityC** [comment]
This is fixed `gmcp.echo(true)`
