### ISSUE TITLE
Save connection details

### ISSUE THREAD

**Issue by tarkah** [LiquidityC/Blightmud#14]
It'd be nice to be able to save the connection details to a server as a friendly name, that can then be used with `/connect` to easily reconnect to that server. And the ability to list all saved connections. Or maybe an alternative would be to have a "Recently Connected" list?

Would be interested in your preference.

**Comment by LiquidityC** [comment]
I've been using lua scripts for this. But I don't see any harm in actually having in client handling for it.

I'm thinking an additional command `/add_world <name> <host> <port>`
Saves are done in sqlite in the users local datadir (we already use this for client logs).

How does that sound?

**Comment by tarkah** [comment]
Yeah, that sounds great. Would you want `/connect <name>` to work, or a separate command, `/load_world <name>` ? And then either working eventually with tab completion would be awesome.

**Comment by LiquidityC** [comment]
It's slightly more fiddly to implement "/connect <world>" but I think it's also slightly more userfriendly so I think that's the way to go.

I think we have the following spec now:

**Specification**
- Implement the command `/add_world <name> <host> <port>`
- Implement the command `/connect <world>` without breaking regular connect functionality
- Add sqlite support (rusqlite is a good crate)
- Create and store the db in the user datadir (logging is already placed there)
- Update documentation for this command (should probably put this on the welcome.md as well)
- Write some tests that run through the commands

@tarkah You want to attempt to build this or just leave it open and I'll get to it eventually?

**Comment by tarkah** [comment]
Perfect, I'll go ahead and build this. Any reason you prefer sqlite over just ser/deser to file? This should be pretty lightweight, unless you plan on utilizing sqlite for other features in the future?

I already mocked up something simple for saving to file. `SaveData` can be impl'd on anything else you want to save / load from the data directory.

```rust
#[derive(Debug, PartialEq, Deserialize, Serialize)]
pub struct Connection {
    pub host: String,
    pub port: u16,
}

type Connections = HashMap<String, Connection>;

pub trait SaveData: Sized + DeserializeOwned + Serialize + Default {
    fn relative_path() -> PathBuf;

    fn save_path() -> Result<PathBuf> {
        let mut data_dir =
            dirs::data_dir().ok_or_else(|| format_err!("Could not get data directory"))?;
        data_dir.push("blightmud");

        let save_path = data_dir.join(Self::relative_path());

        if let Some(save_dir) = save_path.parent() {
            std::fs::create_dir_all(save_dir)?;
        }

        Ok(save_path)
    }

    fn load() -> Result<Self> {
        let save_path = Self::save_path()?;

        if save_path.exists() {
            let file = fs::File::open(&save_path)?;

            Ok(ron::de::from_reader(&file)?)
        } else {
            Ok(Self::default())
        }
    }

    fn save(&self) -> Result<()> {
        let data_string = ron::ser::to_string(&self)?;

        fs::write(Self::save_path()?, data_string)?;

        Ok(())
    }
}

impl SaveData for Connections {
    fn relative_path() -> PathBuf {
        PathBuf::from("data/connections.ron")
    }
}

```

**Comment by LiquidityC** [comment]
No reason for SQLite at all. I’m just used to working with larger data sets. Serde makes a lot more sense for this kind of storage so yeah go with serde. It’s better to have human readable configs as well. 

Thanks!
