### ISSUE TITLE
Can't copy from terminal with 2.1.0, works in 2.0.1

### ISSUE THREAD

**Issue by dmytri** [LiquidityC/Blightmud#148]
I can't select and copy text from the terminal with 2.1.0, but it works in 2.0.1. Is this a bug or there a new setting?

**Comment by LiquidityC** [comment]
We have noticed this. It's a side-effect from adding mouse scrolling. I'm not sure how to deal with it yet because I miss it too but I also enjoy having mouse scrolling.

**Comment by dmytri** [comment]
Well if it's one or the other maybe a setting?

**Comment by LiquidityC** [comment]
I'll do some digging when I get some time over. Preferably I'd like to have some sort of fall through for the events.

**Comment by xvxx** [comment]
This is a bummer. As far as I can tell, the situation is that most terminals send arrow keys when the scroll wheel is used in an alternate buffer terminal app. The new scroll-wheel PR works by enabling mouse events, but there doesn’t seem to be any “fall through” option like there would be in JS.

I’ve been looking for terminal apps that 1) use the alternate buffer 2) allow scrolling with the mouse wheel and 3) allow native selecting of text. It does seem to be a rare combo.

In vim I get the worst of both worlds: my mouse wheel just seems to send arrow keys, and selecting text selects it in vim’s visual mode as opposed to my terminal’s default text selection. 

There is a lot online about tmux’s internal scrollback buffer. I think they hit all three criteria above by implementing their own text selection.

I am going to do some more research too. Maybe we can just add some simple text selection and mouse click detection, if we need to.

**Comment by xvxx** [comment]
The other option would be to tell people that the mouse scrolling issue is a setting they can change in their terminal, and provide an FAQ. Assuming that’s true. Seems like at least iTerm2 surfaces this setting:

https://stackoverflow.com/questions/36594420/how-can-i-turn-off-scrolling-the-history-in-iterm2

**Comment by LiquidityC** [comment]
`set mouse=a` or `set mouse=nvi` gives me good scrolling in vim using gnome-terminal. Sort of besides the point though. I'll do some digging but from what I can tell this will be a tricky one. Simple selection will probably be tricky.

**Comment by Xandaros** [comment]
I use this in my config for mouse scrolling:
```lua
blight:bind("\u{1b}oa", function()
    blight:ui("scroll_up")
end)

blight:bind("\u{1b}ob", function()
    blight:ui("scroll_down")
end)
```
So switching to a mouse terminal is not required for mouse scrolling.
Although it would be required to get other mouse events...

**Comment by xvxx** [comment]
@Xandaros That only works in terminals which don't swallow the scroll wheel when a program is in alternate mode. I get the same behavior as you with Alacritty, but not with Terminal.app or Kitty. 

This seems to be what the "convert scroll to arrow" crew is doing: https://terminalguide.namepad.de/mode/p1007/

You "should" to be able to disable it by sending `?1007l`, where `l`  = `low` to disable the feature, but that doesn't seem to work in my terminal.

**Comment by Xandaros** [comment]
Ah, yes. I am indeed using alacritty.

Might have to implement our own highlighting, then...

**Comment by xvxx** [comment]
Just for the record, here is what `MouseTerminal` from termion does: https://github.com/redox-os/termion/blob/a448f510/src/input.rs#L177

It sends multiple mouse modes, and the terminal is supposed to always use the most recently sent mode that it can support.

The modes in question:

- 1000: [Mouse Down+Up Tracking](https://terminalguide.namepad.de/mode/p1000/)
- 1002: [Mouse Click and Dragging Tracking](https://terminalguide.namepad.de/mode/p1002/)
- 1015: [Mouse Reporting Format URXVT](https://terminalguide.namepad.de/mode/p1015/)
- 1005: [Mouse Reporting Format Digits](https://terminalguide.namepad.de/mode/p1006/)

**Comment by LiquidityC** [comment]
Good info. I'm still on the fence here. I'll take a look at what can be altered in gnome-terminal. On one side I find myself using the scrolling quite a bit. On the other I've realized how much I copy paste when creating triggers etc. A help file with setups for various terminal types may be an option. I think loss of copy/paste is worse than not being able to scroll with mouse tbh

**Comment by dmytri** [comment]
I basically can't upgrade, because I don't have email password delivery set up for new users, so need to copy and paste the new users password from the terminal output each time :laughing: 

Meanwhile, I hardly ever scroll with the wheel. So a setting here would work great for me.

**Comment by xvxx** [comment]
Sorry about that @dmytri, I didn't test this patch thoroughly enough before submitting it!

I agree it would be a good idea to put this behind a config option, maybe "Experimental Mouse Support", and not enable it by default until it's solid.

For people using terminals that don't take over the scroll wheel in alternate mode, we can add those shortcuts @Xandaros wrote as defaults and they'll be good to go.

For others like me using Kitty - when I enable this patch, I can hold down shift+select to do copy and paste. So I would probably leave it turned on for now.

For people like @LiquidityC, we can keep searching for the ideal solution. 😔

**Comment by LiquidityC** [comment]
I think that would be best for now.

Let's drop in an opt in feature for this scrolling.

**Comment by xvxx** [comment]
@LiquidityC I am on it

**Comment by LiquidityC** [comment]
This has been fixed to an opt in solution now. Closing.
