### ISSUE TITLE
Crash when trying to display a single long line with no spaces.

### ISSUE THREAD

**Issue by lisdude** [LiquidityC/Blightmud#15]
When you display a single string of characters with no spaces, the client will unceremoniously crash. This seems to happen around 1,000 or more characters.

If you're a MOO guy, you can reproduce it with this eval:
;;str = ""; chars = strsub($string_utils.ascii, " ", ""); for x in [1..2000] str = tostr(str, chars[random($)]); $command_utils:suspend_if_needed(0); endfor player:tell(str);

**Comment by LiquidityC** [comment]
This is caused by the custom line wrapping we use. Should be pretty easy to force a wrap in cases where we can’t find any spaces.

The reason we use custom is because I couldn’t find a library that doesn’t take escape sequences into account when calculating line length.
