### ISSUE TITLE
Access to debug library

### ISSUE THREAD

**Issue by Xandaros** [LiquidityC/Blightmud#154]
The debug library can be used for all sorts of shenanigans and rlua states that some of its safety guarantees might break if the debug library is used.
Nonetheless, I would like it to be available, since there are a few really useful functions in there.

In particular, I would like access to `debug.traceback`, so I can print a proper error message after a failed pcall.

**Comment by LiquidityC** [comment]
This is new to me. Do you have any links with information about this? Both debug library in general and the rlua thing?

**Comment by Xandaros** [comment]
My statements regarding rlua were mostly taken from the `new_with_debug` function: [Docs](https://docs.rs/rlua/0.16.1/rlua/struct.Lua.html#method.new_with_debug)

`debug` is a standard library that allows you to inspect and change basically the entire Lua state: [Docs](https://www.lua.org/pil/23.html)
`debug.traceback` is a nicely formatted string showing all the different callers - basically what you see when a Lua error happens. Since it needs to inspect the stack, it is in the debug library.
`debug` also allows you to do a lot of other shenanigans, like changing local variables you don't have access to, etc. Most of the debug library is stuff you don't really need most of the time, but some of it could be useful.

**Comment by LiquidityC** [comment]
Cool, how would one want this? Be able to toggle it on when blightmud is started or should it be permanent? My initial feelings are that it isn't something we want enabled by default. We only have one chance to set it. And that's when blightmuds lua state is created.

**Comment by Xandaros** [comment]
Well, my stance is that it's a standard Lua library and should be available by default, but I'm not too bothered if you make it a flag or something, either.

**Comment by xvxx** [comment]
I mentioned [CC:Tweaked](https://tweaked.cc/) (Minecraft mod) in another issue - they enable `debug` by default.

Another Lua-based Minecraft mod, [OpenComputers](https://ocdoc.cil.li/ ), enables a limited version - only `debug.stacktrace` and `debug.getinfo`.

When you install Lua from a package manager, it usually has `debug` enabled.

I don’t have a strong opinion either way, just sharing some prior art.

The Lua docs do mention that you can load up your Lua environment with `debug` enabled and just turn it off in Lua if you want:

```lua
debug = nil
```

So if you want to start with a config option we could in theory just have a single Rust code path and do the enable/disable in Lua.

**Comment by LiquidityC** [comment]
Let's enable this. It's up to the user to do what he or she likes. We shouldn't obstruct that if it won't hurt us either way.
