### ISSUE TITLE
Freeze when hitting up arrow before connecting.

### ISSUE THREAD

**Issue by lisdude** [LiquidityC/Blightmud#16]
If you hit the up arrow on the welcome screen, the input bar will say "thread '<unnamed>' panicked at 'Out of bounds access'  etc etc. From here there doesn't seem to be any way to interact with the client again.

**Comment by LiquidityC** [comment]
Sounds like a basic bug. Should be a pretty quick one-line fix. I’ll check it out unless someone beats me to it.

**Comment by LiquidityC** [comment]
This one is fixed. 2 lines of code :smile: 

Thanks for posting all these bug-reports. I'm not a great tester and you get sort of project blind when building applications. Also, as has been made clear there are a lot of muds with behavior that I have never heard of.
