### ISSUE TITLE
Duplicate Core.Hello and option state not resetting after disconnection

### ISSUE THREAD

**Issue by envis10n** [LiquidityC/Blightmud#162]
**Describe the bug**
On first connect, Core.Hello is sent twice when GMCP is enabled. Server sends WILL GMCP, Client responds DO GMCP, Core.Hello is then sent twice.

After disconnecting and reconnecting, the client responds to WILL GMCP with DONT GMCP. This persists until blightmud is restarted.

**To Reproduce**
Watch the server side of the connection, connect -> disconnect -> reconnect  and watch the response from the client.

**What terminal are you using?**
Windows Terminal (Ubuntu 20.04 WSL)

**What mud were you playing?**
envis10n.dev:13390 (Test server for a MUD project I'm working on)

**Screenshots**
Client Side
![image](https://user-images.githubusercontent.com/8516759/97594192-68f96980-19d0-11eb-9c44-c5869385fffb.png)

Server Side
![image](https://user-images.githubusercontent.com/8516759/97594215-71ea3b00-19d0-11eb-829b-909e06e4b8ac.png)

**Comment by LiquidityC** [comment]
I have noticed an issue that is most likely related to this when using msdp. The first problem is that the active configuration for the telnet parser probably isn't copied correctly when a new parser is initiated. Either on connect or disconnect. Not certain when it happens.

The second issue I'm not to sure about. It's either a bug in the gmcp module or the protocol initiation is triggered twice for some reason.

**Comment by envis10n** [comment]
Okay, at least it's not likely on my end. I'll see if I have time later to take a look through the source and at least try to figure it out.

Is the problem with copying parser config state an issue on the libtelnet side?

**Comment by LiquidityC** [comment]
No. Shouldn't be. It's a bug caused when I added subnegotiation fall through to lua. Essentially all subneg protocols can be added and handled through lua now and that's what we do for gmcp and msdp.

**Comment by LiquidityC** [comment]
Take a look at gmcp.lua and you should get the gist of it

**Comment by envis10n** [comment]
Hmm I also notice Core.Supports is never sent over, though it is defined in the lua file for register.

**Comment by LiquidityC** [comment]
Do the register in a on_ready callback. If you send it before lua handshake it won't transmit

**Comment by LiquidityC** [comment]
Ok, well I know how to fix the first part. I just need a good way of copying what's supported from one parser to the new one. Leaving out all the bits that are set during negotiation.

For the **double Core.Hello** problem I am unable to recreate this. Could you doublecheck on your end that the handshake isn't sent twice or something. Because I can't find any possible loops on my end.

**Comment by envis10n** [comment]
Looks like the double issue is a problem with the parse on my end, as I'm only getting the one subnegotiation.

**Comment by LiquidityC** [comment]
Thanks for that info. I'll drop that then :smile:

**Comment by LiquidityC** [comment]
Ok. I added a method to your lib that enables resetting of local and remote state. This way we don't need to create a new parser on disconnect. We can just reset the one we have. envis10n/libtelnet-rs#17

If this PR is OK and approved I have a fix waiting :smile: 
If there are issues we can maintain this state in blightmud but it will take a bit longer.
