### ISSUE TITLE
Disabling NoPrompt mode has too much impact on some MOOs

### ISSUE THREAD

**Issue by LiquidityC** [LiquidityC/Blightmud#167]
**Describe the bug**
After disabling `NoPrompt` mode in the source the impact has been rather large
on certain MOO's where the output now looks very garbled.

**What mud were you playing?**
toastsoft.net:1443

**Screenshots**
@lisdude Could you extend with your screenshots?

**Comment by lisdude** [comment]
<img width="872" alt="Screen Shot 2020-10-30 at 11 45 49 PM" src="https://user-images.githubusercontent.com/4994688/97772272-8edb5700-1b13-11eb-8097-a6d28ee8fcd3.png">
<img width="872" alt="Screen Shot 2020-10-30 at 11 42 10 PM" src="https://user-images.githubusercontent.com/4994688/97772274-90a51a80-1b13-11eb-8e1a-0454a74fd7ac.png">

**Comment by LiquidityC** [comment]
To start. We'll extend Blightmud to be more verbal about what prompt mode it's using.
Eg. `[**] Setting prompt mode 'TerminatedPrompt'`

Then we will add a method `core:prompt_mode(modestr)` allowing a user to force this.

There will be one exception. If the mud is sending `EOR` or `GA` then `TerminatedPrompt` will be forced ignoring the users setting.

We'll also introduce a helpfile `prompt` explaining how and why things work as they do.

**Comment by LiquidityC** [comment]
Ok, before I proceed with this one I took a swing at fixing the core problem. That weird newlines due to content being split into multiple packets appear in the output. The fruit of my labor can be found under the `test_rogue_nl_fix`.

I'm not 100% sure it holds up. But if anyone can confirm that it @lisdude :smile: . So Would you be willing to compile and test this branch on toaststunt?

**Comment by xvxx** [comment]
FWIW I was seeing random newlines in one of my “simple” MUDs that had the prompt issue, and those have all gone away. It’s looking nice!

However, I don’t see my own input. When I type a command, it shows up for a second (the yellow text prefixed with `> `), but it gets overwritten when the MUD sends me a response.

It looks like it’s an off-by-1 error because if the MUD response is shorter than what I typed, I can see the remainder of my input on the same line:

Like if I type `powerup` and it sends back `Done.`, I see:

    > powerup

For a split second, and then:

    > Done.up
    
The `up` is still yellow, too.

**Comment by LiquidityC** [comment]
Ah, good input. Thanks for that. I'll take a look

**Comment by LiquidityC** [comment]
I fixed the "overwriting the input line" problem. Leaving as is for a while. Currently this is the branch I'm running locally when I play. So let's let it ride for a while and make sure there are no mysterious quirks before we merge. The one downside is that I find the Screen logic slightly to messy for comfort now. So before I do any future changes to the screen code I will want to re-write it to be more readable. But for now well stick to the, **If it aint broke don't fix it** policy.

**Comment by lisdude** [comment]
So far this seems to have fixed the random newlines! At least for incoming text. When you page up the buffer, the newlines all appear with a vengeance.

**Comment by LiquidityC** [comment]
Odd I confirmed that in the original patch. Must have messed something up in the last commit. I'll see if I can find what I broke.

**Comment by LiquidityC** [comment]
Ok, I've tried and I've tried to recreate the whole **roguew newlines in scrollback history** but I can't seem to work it out. Could you help me out with a testenv @lisdude ?

**Comment by lisdude** [comment]
Sure! lisdude.com:1180 (or 1138 TLS)

You can reproduce it by typing 'longline2' and then scrolling up.

**Comment by LiquidityC** [comment]
Thanks. That helps a ton

**Comment by LiquidityC** [comment]
Ok, I don't see any weird linebreaks and no mysterious lines any longer. Not when printing and not when scrolling. Care to take another look @lisdude ?

**Comment by lisdude** [comment]
Now I'm getting an issue where some text coming in isn't pushing the output up, it's overwriting the last line. I've added an 'overwrite' command to my test server to demonstrate it.

But it looks like scrolling is working now!

**Comment by LiquidityC** [comment]
Ha! Stupid me. I completely fixed that last error wrong. It was displaying blank lines but only in scrollback. The reason was that it was pushing the prompt into the output history. So now I've corrected the right error. To my eyes it looks pretty good now. I've also been playing with this a bit in my spare time and it's a real improvement for other muds that don't send IAC GA as well.

Thanks for all the help with the testing @lisdude ! I hope everything will look nice now.

**Comment by lisdude** [comment]
It looks great! Thanks for thinking about us poor MOO folks.

**Comment by LiquidityC** [comment]
Well I don't want to be the guy who dangles something working in front of those who need and then snatch it away. Also this fix is a great improvement even for *non-moos*. The broken lines were an issue there before we made them an issue for you guys (again). But with this fix nobody should have the issue any longer. I'll go ahead and merge this into *dev* sometime soon. After that I'm releasing 2.3.
