### ISSUE TITLE
Lua Script error connecting to Evennia-based MUD

### ISSUE THREAD

**Issue by thedandroid** [LiquidityC/Blightmud#168]
**Describe the bug**
Connecting to an Evennia-based MUD gives this script error:
```
[!!] [Lua] Script error:
[!!] 	runtime error: [string "?"]:14: attempt to perform arithmetic on a nil value (local 'split')
[!!] 	stack traceback:
[!!] 		[C]: in metamethod '__sub'
[!!] 		[string "?"]:14: in upvalue 'parse_gmcp'
[!!] 		[string "?"]:46: in field '_subneg_recv'
[!!] 		[string "?"]:99: in function <[string "?"]:98>
```

**To Reproduce**
Connect to an Evennia-based MUD, such as demo.evennia.com:4000 and login

**What terminal are you using?**
MacOS Terminal.app, Hyper, Alacritty, all consistent in error

**What mud were you playing?**
demo.evennia.com:4000

**Comment by LiquidityC** [comment]
Hmmm. Problem With the gmcp module. I'll check it out later. For now you can set `core:disable_protocol(201)` in config or through the lua command to get around the error.

Are you compiling from the dev branch?

**Comment by thedandroid** [comment]
No, I'm using 2.2.0. Sorry, should've included that info.

**Comment by LiquidityC** [comment]
Ok, found the issue have a fix. Evennia doesn't seem to be conforming to the standard GMCP proto. Or perhaps I'm mistaken. I'll put together a new release tonight and update homebrew tap etc.

**Comment by LiquidityC** [comment]
Homebrew tap updated and new release with patch is out.
