### ISSUE TITLE
Scrollback "sticks" with very long lines.

### ISSUE THREAD

**Issue by lisdude** [LiquidityC/Blightmud#17]
When you have a single line that encompasses several screens of scrolling, the top half or so of the line will stick to the top while the bottom scrolls. Eventually it will catch up and scroll properly. Additionally, it seems the top part of the line will disappear entirely when you scroll back to the beginning. The line is question is 31,542 characters long.

![scrolling](https://user-images.githubusercontent.com/4994688/82270363-2cfaac80-993a-11ea-90b2-4c5462668eec.gif)

I hope this terrible gif helps demonstrate what I mean.

**Comment by LiquidityC** [comment]
The “history” bidder for scroll back is only 1024 lines long so you might be seeing an effect of that here. 

Regarding the sticky line this could the client or it could be your terminal not keeping up. 

Could you explain how you confirm/test this?

We might need to build a super simple telnet server to be able to test these kind of things.

**Comment by lisdude** [comment]
I tested this with Kitty and the macOS Terminal and it happened in both cases.

I've setup a test server at lisdude.com port 1180. Right now there are two commands:
  longline  A single 31,527 character string of real-world output.
  random    A random string with no spaces, configurable between 1 and 50,000 characters.

If you can think of more tests we need, I'm happy to add them. Right now, when you run the longline command, you can see that it cuts off the login help text and part of the long line itself. (For reference, the line begins with ";properties(#0)"

**Comment by LiquidityC** [comment]
That is awesome! By the looks of it it seems the history is messed up here and the last lines in the history consist of an "unwrapped" line. At least I have something to work with here. I'll look into it some more.

**Comment by LiquidityC** [comment]
Just a comment to remind me for later. This might be the prompt acting up. On Servers that don’t send IAC GA we have to guess what’s a prompt when the data stops coming. A simple check here should be that what we think is a prompt is shorter than an arbitrary width. Eg. if it’s longer then 100 chars with no new lines it’s probably not a prompt.
