### ISSUE TITLE
Reconsider macOS config dir

### ISSUE THREAD

**Issue by xvxx** [LiquidityC/Blightmud#173]
Maybe this ship has sailed, but I disagree with the `dirs-next` crate's decision that `~/Library/Application Support` should always be the default config directory on macOS.

This is from their docs:

```
dirs_next::config_dir();
// Lin: Some(/home/alice/.config)
// Win: Some(C:\Users\Alice\AppData\Roaming)
// Mac: Some(/Users/Alice/Library/Application Support)
```

I believe that for UNIXy command line programs which are not specific to macOS, the default config dir should be `~/.config` (and therefor `~/.config/blightmud`).

I don't think there's a "right" answer here, but this behavior would match other UNIX programs which aren't unique to Mac:

```
$ ls -1 ~/.config/
Unreal Engine/
asciinema/
configstore/
fish/
hub
kitty/
mpv/
mudlet/
phetch/
spotify-tui/
twtxt/
```

Meanwhile, `~/Library/Application Support` is almost exclusively used by native macOS applications which live in `/Applications` and usually get launched through the GUI.

My `~/Library/Application Support` is pretty big, but there's only two command line programs which use it - `nu` and `blightmud`, presumably because they both use `dirs-next`.

The rest are all native and builtin apps, and even the ones that look like UNIX commands (`fman`, `transparencyd`(?)) aren't in my `$PATH` so I can't launch them from a shell:

```
$ ls -1 ~/Library/Application Support
Acorn
AddressBook
Ascii Sector
CEF
CLion2019.2
CallHistoryDB
CallHistoryTransactions
Clipy
CloudDocs
CoreParsec
CraftOS-PC
CrashReporter
DiskImages
Dock
Electron
FileProvider
Hyper
IPFS Desktop
JREInstaller
JetBrains
Knowledge
OpenEmu
OpenVR
Oracle
Pock
Quick Look
RustPlayground
Slack
Sonos
SonosV2
Soulver
Spotify
blightmud
ccemux
com.apple.AssistiveControl
com.apple.ContextStoreAgent
com.apple.ProtectedCloudStorage
com.apple.TCC
com.apple.backgroundtaskmanagementagent
com.apple.kvs
com.apple.replayd
com.apple.sharedfilelist
com.apple.spotlight
com.apple.touristd
com.apple.transparencyd
com.clipy-app.Clipy
com.pigigaldi.pock
com.sonos.macController
com.sonos.macController2
dmd
fman
icdd
minecraft
nu
org.openemu.OEXPCCAgent.Agents
syncdefaultsd
transparencyd
```

Some may say "just symlink it", but if you're keeping `~/.config` under version control and sharing it between computers the symlink adds an unecessary headache.

Also, I mean - who the heck puts _whitespace_ in a UNIX directory name? C'mon Apple.

I'm not sure if there's a clean way to make this change moving forward, so I wanted to open this issue and see if there's appetite before getting too into it.

**Comment by LiquidityC** [comment]
Damn that's weird.

Do we have any access to change this config? Because I'm completely fine with switching this. We'll just have to bump the major version instead of the minor and provide information. Same way I did with GMCP changes.If not, then perhaps we should drop dirs-next and roll our own thing. As long as we can get access to $HOME-path we can just path it out from there and drop a dependency while we're at it. I really don't care if it gets weird on Windows. Also windows users are stuck with WSL and in WSL it should be fine either way.

**Comment by envis10n** [comment]
Yes,, windows users are stuck with WSL which should just act the same as UNIX in this instance.

**Comment by xvxx** [comment]
> Do we have any access to change this config?

I don't see a way to change it in the `dirs-next` crate, looks like they hardcode the path: https://github.com/xdg-rs/dirs/blob/11e50cbb/src/mac.rs#L13

Coincidentally, they [just switched](https://github.com/xdg-rs/dirs/blob/master/CHANGELOG.md#200---2020-10-22) from `~/Library/Preferences` to `~/Library/Application Support` in a recent release, so I am not sure they have fully vetted the Mac support yet.

One thing we could do for a smooth transition on macOS is check for `~/Library/Application Support/blightmud` on startup and use it if it exists, otherwise use `~/.config/blightmud`. Maybe print a warning: "You are using the old macOS config dir. Support for it will be removed in a future version." Then we don't need to do the big version bump just yet, nor break existing installs.

On the `$HOME` note, I think you could also consider dropping the dependency on the `shellexpand` crate as part of this. Most modern shells set `$HOME`, and I don't think it's too much to ask someone to set it if it's not there.

Then the `shellexpand` call could just be something like this:

```rust
if path.starts_with('~') {
    path.replace("~/", env::var_os("HOME"))
}
```

**Comment by LiquidityC** [comment]
That sounds like a good plan. Let's do it like this:

- Drop `dirs-next` and `shellexpand` crates and add our own handling
- On start we check if `~/Library/Application Support/blightmud` exists. If it does then use that as config dir and show a warning.
- Default all config and data paths to `$HOME`. This is currently `.config` and `.local`
