### ISSUE TITLE
Large amounts of GMCP mess up and content gets printed on screen.

### ISSUE THREAD

**Issue by LiquidityC** [LiquidityC/Blightmud#174]
Some muds eg. Stickmud send giant bulks of gmcp data. Sometimes this bugs out and parts of that data get printed as regular mud content. I located the issue for this in `libtelnet-rs` and I submitted a PR.

This issue is only here to track that and the adaptations we might need to do.

This is the PR: envis10n/libtelnet-rs#18

**Comment by envis10n** [comment]
Fix merged. I'll push an update once I get to my desk
