### ISSUE TITLE
Add Lua bindings for rust regex

### ISSUE THREAD

**Issue by Xandaros** [LiquidityC/Blightmud#176]
Lua has pattern matching, but... it leaves a lot to be desired.
Since we are already using the `regex` crate, maybe adding bindings to that might be a good idea?

Users can still choose whether they use Lua's pattern matching or rust's regex, but it allows access to a more powerful regex library.

Especially since rust's regex is already used for triggers and such, but there is currently no way to utilise it directly.

**Comment by LiquidityC** [comment]
If someone wants to take a swing at this I'd like it to work like this:
- Create a regex object (`UserData`) that is returned from the method `regex(pattern)` in lua.
- The regex object should have a `match(string)` method that returns `matches`
- The regex object should also have a `test(string)` method that just returns true or false.

**Comment by LiquidityC** [comment]
Perhaps a `replace(source, replacement)` method could be added to the regexp object as well if you can make it work
