### ISSUE TITLE
Blightmud crashes on startup

### ISSUE THREAD

**Issue by MadMatt04** [LiquidityC/Blightmud#18]
**Describe the bug**
For a moment, the UI blinks and tries to take over the terminal, then crashes.

**To Reproduce**
Run it on MacOS Catalina 10.15.4 with zsh with Oh My Zsh installed, rustc 1.43.1 (8d69840ab 2020-05-04)
[log.txt](https://github.com/LiquidityC/Blightmud/files/4650025/log.txt)

**What terminal are you using?**
MacOS Terminal with zsh and Oh My Zsh installed.

**Comment by LiquidityC** [comment]
Hmmm. From what I have read just now termion (backend lib) should be ok on mac os terminal and mac os terminal should support vt102 which is what termion and blightmud use to talk to the tty.

I don't have a mac otherwise I'd love to debug this. Anyone good with mac and debugging rust?

Figure a breakpoint in the main loop and then some stepping should present the problem rather quickly.

**Comment by LiquidityC** [comment]
Did you try running "cargo test"? We might get lucky :smile:

**Comment by MadMatt04** [comment]
Tests seem ok.  

Blightmud git:(master) ✗ cargo test
   Compiling blightmud v0.1.0 (/Users/matijak/Documents/GitHub/Blightmud)
    Finished test [unoptimized + debuginfo] target(s) in 19.78s
     Running target/debug/deps/blightmud-c1193b935b0bc97c

running 10 tests
test command::command_test::test_editing ... ok
test screen::screen_test::test_wrap_line ... ok
test help_handler::help_test::file_not_present ... ok
test output_buffer::output_buffer_tests::test_prompt_capture ... ok
test output_buffer::output_buffer_tests::test_line_capture ... ok
test lua::lua_script::lua_script_tests::test_lua_alias ... ok
test lua::lua_script::lua_script_tests::test_lua_trigger ... ok
test lua::lua_script::lua_script_tests::test_lua_prompt_trigger ... ok
test screen::screen_test::test_long_line_no_space ... ok
test help_handler::help_test::confirm_markdown_parsing ... ok

test result: ok. 10 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

**Comment by MadMatt04** [comment]
Here is the stack trace from running this in CLion. It dies where you do Screen::new() in run() in main.rs

thread 'main' panicked at 'attempt to subtract with overflow', src/screen.rs:29:27
stack backtrace:
   0: std::sys_common::at_exit_imp::push
   1: <&mut W as core::fmt::Write>::write_fmt
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
   6: std::panicking::try::do_call
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::panicking::panic
             at src/libcore/panicking.rs:52
   9: blightmud::screen::Screen::new
             at src/screen.rs:29
  10: blightmud::run
             at src/main.rs:89
  11: blightmud::main
             at src/main.rs:77
  12: std::rt::lang_start::{{closure}}
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libstd/rt.rs:67
  13: std::panicking::try::do_call
  14: panic_unwind::dwarf::eh::read_encoded_pointer
  15: std::panicking::rust_panic_without_hook
  16: std::rt::lang_start
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libstd/rt.rs:67
  17: blightmud::run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Comment by MadMatt04** [comment]
![image](https://user-images.githubusercontent.com/3851805/82323406-4c481700-99d8-11ea-8365-44e70a12f324.png)

The height and width of Screen are 0, which then causes an overflow error when you try to do height - 2.

**Comment by MadMatt04** [comment]
Ok, this last crash with the screenshot might be related to apparently running in a different console with the debugger, because if I run it with cargo run the width and height are determined to be 2500 and 25 and there is a different stack trace:

W, H: 2500, 25
════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━thread 'main' panicked at 'attempt to subtract with overflow', src/screen.rs:335:23
stack backtrace:
   0:        0x109c8578f - std::sys_common::at_exit_imp::push::he92152db20c20630
   1:        0x109ca852e - <&mut W as core::fmt::Write>::write_fmt::h996f2167e21ff3f9
   2:        0x109c7fcf7 - std::io::Write::write_fmt::h9197012b9d65a9a3
   3:        0x109c8777a - std::panicking::default_hook::{{closure}}::h7b209cdc44c5777f
   4:        0x109c874bc - std::panicking::default_hook::hf135bc502e6f77db
   5:        0x109c87de8 - <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get::h100fb34c1f9a36b5
   6:        0x109c879b2 - std::panicking::try::do_call::he58e98df0f664580
   7:        0x109cb6b5f - core::panicking::panic_fmt::h9eea9e4965bd189c
                               at src/libcore/panicking.rs:85
   8:        0x109cb6ab7 - core::panicking::panic::ha1b08da3ff863883
                               at src/libcore/panicking.rs:52
   9:        0x109545c34 - blightmud::screen::wrap_line::hdb136907594aff8b
                               at src/screen.rs:335
  10:        0x109543eb2 - blightmud::screen::Screen::print_output::hfbe8ccc9c1bbd00b
                               at src/screen.rs:162
  11:        0x10947717f - blightmud::event::EventHandler::handle_output_events::ha8202cc99847ac76
                               at src/event.rs:161
  12:        0x109526e7f - blightmud::run::h37da744e8dab76c9
                               at src/main.rs:116
  13:        0x1095265b7 - blightmud::main::h306b8b07dfac0d22
                               at src/main.rs:77
  14:        0x10952086e - std::rt::lang_start::{{closure}}::hce3cb76e79fbec0f
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libstd/rt.rs:67
  15:        0x109c878b8 - std::panicking::try::do_call::he58e98df0f664580
  16:        0x109c8f00b - panic_unwind::dwarf::eh::read_encoded_pointer::hb2604fbe8c357c34
  17:        0x109c882ba - std::panicking::rust_panic_without_hook::hc11f1415e808dade
  18:        0x109520851 - std::rt::lang_start::hf0891bc99941fcf0
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libstd/rt.rs:67
  19:        0x1095292e2 - blightmud::run::h37da744e8dab76c9

Process finished with exit code 101

**Comment by LiquidityC** [comment]
Ok, thanks a bunch man.

That really helps. So 'termion' fails to retrieve your terminal dimensions and that's what's messing up. There is a lot of stuff that those dimensions are needed for. So the solution here is to figure out and solve the failiure to retrieve the dimensions from your terminal.

On another note this issue has made me aware that the error handling and logging is garbage. I'm adding an issue for that. This crappy handling won't do :smile:

**Comment by LiquidityC** [comment]
I'll either have to dive into termion to figure out this error or try and find a lib for fetching terminal sizes that's consistent on both mac and linux.

**Comment by MadMatt04** [comment]
I now ran it completely outside CLion and got yet a third set of values for width and height, which seems to be OK:

[00:00:00.000] (112c3bdc0) INFO   Starting application
[00:00:00.001] (7000041a6000) DEBUG  Input stream spawned
[00:00:00.002] (112c3bdc0) INFO   W, H: 226, 25
log.txt (END)

But, the problem is that the crash outputs the stack trace before the terminal exits the graphical mode and therefore erases it before it returns to the normal terminal mode.

**Comment by MadMatt04** [comment]
Ok, it definitely crashes at this line with another overflow error:

![image](https://user-images.githubusercontent.com/3851805/82337618-452b0400-99ec-11ea-8839-a08c5a05a903.png)

**Comment by LiquidityC** [comment]
Yeah, I looked at it properly now. I think I have a fix. I'll look at it closer tonight. Thanks for all the great help

**Comment by LiquidityC** [comment]
There is a new commit in in 5 mins that might fix your problem. Otherwise I'll check more tonight

**Comment by LiquidityC** [comment]
Try again otherwise I'll look closer tonight

**Comment by MadMatt04** [comment]
I think you might have forgotten to push, the latest commit is 6 hours old.

**Comment by MadMatt04** [comment]
Temporarily fixed it myself by doing this:
![image](https://user-images.githubusercontent.com/3851805/82339584-7dcbdd00-99ee-11ea-8bff-b2100acb15e1.png)

Seems to be working ok for now.

**Comment by LiquidityC** [comment]
Yeah, my push failed because I was out of sync. Didn't notice that. This confirms my fix though so it should work now. I switched it `last_cut +1 < line.len()` more unlikely to overflow on addition :smile:

**Comment by LiquidityC** [comment]
If my commit fixed your issue then please close this issue. I'm happy we got it working for you. And thanks again for all the data. I need to get a mac for this stuff but those things are pricey :laughing: 

Even though mac was not at fault here.

**Comment by MadMatt04** [comment]
Yeah, the fix works.
