### ISSUE TITLE
Autocomplete only works for 5+ char words

### ISSUE THREAD

**Issue by xvxx** [LiquidityC/Blightmud#182]
**Describe the bug**
Pressing `TAB` seems to only autocomplete words that are 5 or more characters long. 

**To Reproduce**
Type `abcd` and hit enter so it's in the output buffer, then type `ab` and press `TAB`. It doesn't do anything.

Type `abcde` and hit enter so it's in the output buffer, then type `ab` and press `TAB`. It autocompletes to `abcde`.

Not sure if this is intended behavior or not? I noticed this while aliasing `dunemud.net` to `dune` when I couldn't get it to autocomplete.

**Comment by LiquidityC** [comment]
It's done like that intentionally. But It's a one line fix. Or perhaps we should make a setting?

**Comment by xvxx** [comment]
Ahh okay. A setting would be good if some people prefer it to not be too greedy and only match longer words. Personally I would set it to 2+ or 3+ letters myself. Or is it a perf reason for keeping it to 5+?

**Comment by LiquidityC** [comment]
You know what. I was actually wrong here. It's hardcoded into `rs-complete` to exclude words shorter then 5 chars. Luckily it's my crate so we can easily change that to be configurable for the developer and extend with a setting here. Or just configure it to use >2 char words by default.

I set up an issue for `rs-complete` here: liquidityc/rs-complete#1

**Comment by xvxx** [comment]
I took a stab at this in https://github.com/LiquidityC/rs-complete/pull/2, but I think for Blightmud itself it'd be good to start with a default of `2` and not add the setting unless someone specifically wants it. 

Mostly because the settings are just `bool` right now and I'm not sure it's worth adding a number version if no one is going to use it, unless you feel differently.

**Comment by LiquidityC** [comment]
Ok, I merged and published. I'm setting the length to words of 3 and longer. I think 2 is too low, typing a two letter word or typing one char and hitting tab is two key presses. I don't see any time save there.

**Comment by xvxx** [comment]
I’m fine with that but I’d argue that autocomplete isn’t just about speed, it’s also about discovery and helping you remember commands. Most shells let you just hit `TAB` with nothing typed at all to start showing suggestions. Maybe in the future we can beef it up a bit. But this is a big improvement either way 👍🏻
