### ISSUE TITLE
Optimize for multiple instances of Blightmud running at once

### ISSUE THREAD

**Issue by xvxx** [LiquidityC/Blightmud#195]
Apologies for the vague title, just something I've been thinking about. 

It seems like Blightmud has the philosophy of "run one instance of Blightmud per MUD." So instead of supporting tabs and multiple connections per client directly in Blightmud itself, you just fire up a bunch of Blightmud clients in different tabs/windows/tmux/etc/whatever and connect each one to a different MUD.

I love this philosophy, it vastly simplifies the code and leaves the heavy lifting of window management up to the window managers.

However, I think there are a few spots where the code doesn't expect multiple clients to be running at the same time. 

So this is a two part issue:

1. Am I correct in interpreting the philosophy this way?

2. If so, I'd like to help track down any parts of the app which go against this philosophy and update them.

The first one that comes to mind is anywhere files are saved to disk, but there may be more.

Specifically, if you have two clients open and you do `/add_server` in both of them, the second `/add_server` will overwrite the first one. Because saved servers are loaded at boot, not on demand. I haven't checked, but `/settings` might have this same issue.

Obviously this is an easy fix, but I wanted to check in on the philosophy before going on a hunting expedition.

**Comment by LiquidityC** [comment]
Half yes, half no. I've tried to keep the possibility for multiple sessions open while I was building. But I think at a later stage I've decided it's not a direction I want to take. However, whatever we choose, you are right about that overwrite situation. If you have solutions for those they are welcome.

**Comment by xvxx** [comment]
Okay great, that makes sense. I wouldn't be opposed to multi-sessions in the future, but I do love how focused the app is today. :+1: I'll see if I can fix the situations I know about.

And not that you asked, but I would personally be interested in having multiple screens/tabs/something even for the same connection. I'd love to split out chat channels from the main gameplay buffer somehow. Pretty sure I can do this with the status area today if I want, but I really like how WoW did it where you have a little text window that can have different tabs which light up when there is activity...

**Comment by LiquidityC** [comment]
Oh, I do this today.

![Screenshot from 2020-11-07 00-21-36](https://user-images.githubusercontent.com/164039/98423571-539ad400-208f-11eb-8369-1d843ee99f2b.png)

Lua can write to files. Split in tmux with a `clear && tail -f <file>` and you're golden.

**Comment by xvxx** [comment]
Holy moly, it's beautiful.

**Comment by LiquidityC** [comment]
https://gist.github.com/LiquidityC/0fb3d4db78d094be8414eb065504d87f

For the communication writing to file.

**Comment by xvxx** [comment]
This is amazing. brb setting my office LED lights to reflect my character's HP....
