### ISSUE TITLE
ctrl-c no longer quits when `confirm_quit` setting is enabled

### ISSUE THREAD

**Issue by xvxx** [LiquidityC/Blightmud#198]
The `Confirm quit with ctrl-c` prompt stopped working on `dev`, probably because the events we are sending internally got changed.

Right now it expects three events in this order to work:

- `Event::Quit`
- `Event::UserInputBuffer(..)`
- Another `Event::Quit`

If it doesn't get the 2nd `Event::Quit`, it bails. 

It looks like it's now receiving `Event::TimedEvent(10)` after the `UserInputBuffer` event but before the 2nd `Quit` event, so the 2nd `Quit` isn't detected. Not sure if that's intentional or not.

Looks like the change happened in efdadea41fde78f0c1ffda9217226c0c37eba39c

**Comment by LiquidityC** [comment]
TimedEvent. It must be the timer that the task system has running that interrupts.
