### ISSUE TITLE
Add markdown support

### ISSUE THREAD

**Issue by LiquidityC** [LiquidityC/Blightmud#2]
Helpfiles are currently writte in MD. This makes them look good in github but not so much when viewed in the client.

Using this lib: https://github.com/netvl/md.rs we could perhaps improve the look of the markdown files when shown in the client.

Coloring is out, but the other data should turn out better then what we have at least.

**Comment by tarkah** [comment]
Hey, came across your project here from your `help wanted` tag. Looks pretty cool!

There is this library https://github.com/Canop/termimad. It uses `crossterm`, where you look like you're using `termion`, but the library also supports outputting the formatted text with a set width.

As an aside, `crossterm` targets Windows as well. I use it in a TUI project that I made. If you want full cross-platform support, you may want to migrate over to it.

**Comment by tarkah** [comment]
Example to print formatted text:

```rust
use termimad::*;
let skin = MadSkin::default();
let my_markdown = "#title\n* item 1\n* item 2";
let text = FmtText::from(&skin, &my_markdown, Some(80));
println!("{}", &text);
```

**Comment by LiquidityC** [comment]
Yes, I checked that out when I was looking around crates.io earlier. Termimad does a lot of extra rendering that probably won't play nice with my vt102 setup. Particularly the fact that I use scrolling areas and through that split the screen into an input area and an output area. I doubt termimad would respect this configuration.

Thanks for the tip though.

**Comment by tarkah** [comment]
No problem. https://docs.rs/mdcat seems to be another option, though you may face the same limitations outputting to your terminal. Good luck!
