### ISSUE TITLE
Option to disable Ctrl-C

### ISSUE THREAD

**Issue by Xandaros** [LiquidityC/Blightmud#200]
Since there has been a lot activity about the behaviour of Ctrl-C, I thought I'd bring this up.
I personally find it weird that a program like Blightmud quits with Ctrl-C and would like to disable it, but there is currently no way of doing so.

**Comment by xvxx** [comment]
Maybe we could check user keybindings before checking the builtin ones, so you could override all the defaults/Rust keybindings?
