### ISSUE TITLE
Crash when backspacing at the beginning of the input area.

### ISSUE THREAD

**Issue by lisdude** [LiquidityC/Blightmud#21]
**Describe the bug**
The client crashes when backspacing at the beginning of the input line. Thread '<unnamed>' panicked at 'attempt to subtract with overflow', src/command.rs:103:32.

**To Reproduce**
1. Type anything into the input area.
2. Move the cursor to the beginning of the line.
3. Backspace.

**What terminal are you using?**
Kitty

**Comment by LiquidityC** [comment]
This one should be pretty easy to prevent: `src/ui/command.rs:remove()`
