### ISSUE TITLE
Output listeners not triggered for prompts

### ISSUE THREAD

**Issue by Xandaros** [LiquidityC/Blightmud#214]
Output listeners are not triggered for prompt lines. Consider:

```lua
mud:add_output_listener(function(line)
    print(tostring(line:prompt()))
    return line
end)
```

Will have output similar to this on Coffeemud (coffeemud.net 23):
```
       '._     """----.....______.....----"""     _.'
false
          '""--..,,_____            _____,,..--""'
false
                        '"""----"""'
false

false
Welcome to CoffeeMud
false

false
Account name:
Account name:
```

The doubling of the `Account name:` line seems unrelated. I also tested this on starmourn, which does not send the login prompt as an actual prompt line, but the prompts ingame were also not recognised.

**Comment by LiquidityC** [comment]
A line missing from `event.rs:~259`
