### ISSUE TITLE
A Lua method to display text along the bottom bar.

### ISSUE THREAD

**Issue by lisdude** [LiquidityC/Blightmud#22]
As the title says, a way to display your own text in the bottom bar (where (more) shows up while scrolling). This allows for plugins to display and update persistent custom information.

I don't think we need anything fancy, function-wise:

> blight:output_to_bottom_bar(str)
> 
> Prints persistent output to the bottom bar. Space is reserved at the front for (more) when scrolling.
> Eg. blight:output_to_bottom_bar("Assists: 0  Memory: 1.51 GB  Players: 63")
> 
> blight:clear_bottom_bar()
> Clears all text from the bottom bar. "(more)" is unaffected.

Clear is redundant, as you could just output a blank string, but I think it's nice for clarity of what you're intending to do.

**Comment by lisdude** [comment]
This would also be nice to have for the top bar. Dream big!

**Comment by LiquidityC** [comment]
This was on my personal list already. Big Tinfugue fan here. Just need to figure how I want it to perform.

**Comment by LiquidityC** [comment]
Ok. I've finished thinking about this:

**Spec:**
We want something that looks like this:
![Screenshot from 2020-05-26 08-36-07](https://user-images.githubusercontent.com/164039/82871816-69c63500-9f32-11ea-97ac-f975e0e0e791.png)

This requires two new lua methods:
- `blight:set_status_area(height)` Sets the height of the area (0 removes it)
- `blight:set_status_line(index, line)` Prints a line in the status area. Invalid indexes does nothing

**Comment by lisdude** [comment]
Oh, interesting! So you were thinking a whole separate area. I was thinking of something more compact and bottom bar usurping, like this:
<img width="944" alt="Screen Shot 2020-05-26 at 2 57 11 AM" src="https://user-images.githubusercontent.com/4994688/82875189-b2fb9200-9efc-11ea-8e1b-3c50ea926f9b.png">

I like them both for different reasons. Modifying the bottom bar directly is good for out of the way, mostly static information. But a full status area would be good for displaying more dynamically changing information, like character health / status bars and / or a minimap...

Both? 😁

**Comment by LiquidityC** [comment]
We could `blight:set_status_line(index, line)` to write both on the top and bottom line as well as the space between. Allowing users to create an area if they want it and write to that or just write to the existing single line. This means that the status area height will always be >= 1.

So yes, both should work with this solution.
