### ISSUE TITLE
Ignore duplicate commands in a sequence.

### ISSUE THREAD

**Issue by lisdude** [LiquidityC/Blightmud#23]
Instead of every line of input being saved, it would be nice if it checked against the last saved input. If they're the same, don't bother saving it again. This way if you have a lot of lines of the same input, you only have to hit the up arrow twice to get to the command before that instead of 30 times.

e.g.

>\>get pancakes
>\>attack clown
>\>attack clown
>\>attack clown
>\>attack clown
>\>eat pancakes
>\>

In this scenario, you have to hit the up arrow six times to get back to "get pancakes". With this suggestion, it would only save "attack clown" once. So your command history would look like this:

>\>get pancakes
>\>attack clown
>\>eat pancakes

A mere three up arrows away!

**Comment by LiquidityC** [comment]
Already thought of this also. It's in the plans. Thanks for creating the issue :smile:
