### ISSUE TITLE
Autoload a script when connecting to a saved server.

### ISSUE THREAD

**Issue by lisdude** [LiquidityC/Blightmud#31]
Auto-loading a script after connecting would be great for:

- MOOs auto-loading the MCP package.
- Connecting with a saved username / password.
- Auto-loading all of that server's scripts and triggers and aliases and timers and whatnot's without having to remember to /load every time.

**Comment by LiquidityC** [comment]
This is my counter suggestion to this:
- We will engage the config dir for blightmud ($USER/.config/blightmud).
- Any .lua files in this directory will load automatically when you start blightmud
- We will augment the `blight:on_connect(callback)` function to provide the callback with the host and port when triggering. That way you can configure through lua how you want the client to behave.

Example:
```lua
blight:on_connect(function (host, port)
    if host == "lisdude.com" and port == 1180 then
        blight:send("username")
        blight:send("password")
        blight:reset()
        blight:load("/home/username/ws/blight-scripts/lisdude/main.lua")
    end
end)
```

**Comment by boozook** [comment]
For same people as me who find this answer, I've just actualise it a little bit for actual [api][] and also add macOs's KeyChain integration:

[api]: https://github.com/Blightmud/Blightmud/blob/dev/resources/help/mud.md

```lua
local USERNAME = "My username"

local function ask_password(username)
    -- ask macOs's KeyChain for the password:
    local handle = io.popen("security find-generic-password -a " .. username .. " -w")
    local result = handle:read("*a"):match("^%s*(.-)%s*$") -- read & trim
    handle:close()
    return result
end

mud.on_connect(function(host, port)
    if host == "achaea.com" then
        blight.output("Loging as"..C_BLUE, USERNAME..C_RESET)
        mud.send(USERNAME, {
            gag = true,
            skip_log = false
        })
        mud.send(ask_password(USERNAME), {
            gag = true,
            skip_log = true
        })

        -- blight:load("/home/username/ws/blight-scripts/lisdude/main.lua")
    end
end)
```
