### ISSUE TITLE
Calling reset() with a running timer crashes.

### ISSUE THREAD

**Issue by lisdude** [LiquidityC/Blightmud#33]
**Describe the bug**
If you call the reset() function from Lua after a timer has been added, the client will crash the next time the timer runs.

**To Reproduce**
1. crashtest.lua with the content: blight:add_timer(10, 0, function() blight:output("hi"); end);
2. reset.lua with the content: blight:reset();
3. Connect somewhere
4. /load crashtest.lua
5. /load reset.lua

In about 8 seconds, the client will crash.

**What terminal are you using?**
Kitty

**Comment by LiquidityC** [comment]
I thought this might be a problem. Reset should drop all timers as well as the lua state.
