### ISSUE TITLE
Timer output won't display until there is other server activity.

### ISSUE THREAD

**Issue by lisdude** [LiquidityC/Blightmud#34]
**Describe the bug**
When a timer is configured to use blight:output() every second, the text isn't displayed until other text comes in from the MUD. It seems to be indefinitely queued.

**To Reproduce**
1. Create a script.lua file with contents: blight:add_timer(1, 0, function() blight:output("hi"); end);
2. /load script.lua
3. Connect to a quiet server (lisdude.com:1180 is my test environment)
4. Do nothing.

As you do nothing, you'll notice no 'hi' appearing. But if you hit enter, suddenly all of the hi's will appear.

**What terminal are you using?**
Kitty

**What mud were you playing?**
lisdude.com port 1180

**Comment by LiquidityC** [comment]
Oh. Thus is my bad. I’ll fix it today
