### ISSUE TITLE
Use saved name for log file directory

### ISSUE THREAD

**Issue by lisdude** [LiquidityC/Blightmud#35]
Rather than placing log files in a directory named after the server address, could they be put into the saved server name instead? Then it can fall back to naming the directory after the address if it's not a saved server.

So, for instance, we have:
>Saved servers:
>
>- Name: albori, Host: toastsoft.net, Port: 1234
>- Name: will, Host: toastsoft.net, Port: 1234

That would create two directories in /blightmud/logs: albori and will. And if I manually `/connect toastsoft.net 1234` it would then fall back to /blightmud/logs/toastsoft.net.

This comes in handy when you have multiple characters on the same MUD. I regularly connect to at least two (my administrator and my player character) and it would be nice to differentiate the log files for each one.

**Comment by LiquidityC** [comment]
Based on how things are handled this could be tricky. Not unreasonable. Just tricky.

**Comment by LiquidityC** [comment]
A counter solution to this might be to add the following lua commands:
- `blight:start_log(hostname)` Does exactly what `/start_log` command does

If you disable autologging with `/set logging_enabled false` this will let users control logging in whatever way they like.

I think this is a more versatile solution.
