### ISSUE TITLE
blight:output should support colour :)

### ISSUE THREAD

**Issue by robg204** [LiquidityC/Blightmud#51]
having coloured output would be super useful.

**Comment by robg204** [comment]
I realize that it does seem to support embedding ansi sequences in the output line, and I guess I could wrap that in a script, but it feels less good than, say, coutput parsing a tag like <red> or something similar.

**Comment by LiquidityC** [comment]
That’s what I do. But perhaps we could pre-define some color variables in the lua environment so that people don’t have to put in their own. I’ll test out some solutions. Help files need some related updates also. I shouldn’t expect everybody to know ANSI codes.

**Comment by LiquidityC** [comment]
**Spec**
- Update `blight:output` documentation to make it clear that ansi codes work
- When creating the lua state define a bunch of globals for the standard colors. (Eg. C_BLUE, C_RED, ..., C_RESET)
- Define an additional lua method that prepends it's input with the ESC char (\x1b/\033). (Eg. `function ESC(param) -> "\x1b${param}"`
