### ISSUE TITLE
blight:add_trigger ansi trigger support

### ISSUE THREAD

**Issue by robg204** [LiquidityC/Blightmud#52]
being able to trigger on ansi would be great.

**Comment by LiquidityC** [comment]
Can you elaborate on this? You want to be able to create a trigger on a certain line with additional constraint on the color of that line?

**Comment by robg204** [comment]
Basically, yes. In tintin++ this looks something like this:
#action {~\e[45m%*} { ... }

Essentially ~ at the start of a trigger processess the line raw, so that you can match on ansi and the like.

In Mudlet, this looks like just picking the a colour from a palette.

**Comment by LiquidityC** [comment]
Here’s what we can do without much hassle at all: we extend the trigger options with a parameter “raw”, if set to true the trigger will be matched on the original line and not the one with ansi escapes stripped. This will leave it up to the user to work out the correct regexp. Maybe not the easiest handling but it will work as expected.

**Comment by robg204** [comment]
> Here’s what we can do without much hassle at all: we extend the trigger options with a parameter “raw”, if set to true the trigger will be matched on the original line and not the one with ansi escapes stripped. This will leave it up to the user to work out the correct regexp. Maybe not the easiest handling but it will work as expected.

This would be awesome.  Sorry for the bombardment by the way.  Small group of us fed up with decades old tt++ bugs stumbled across your client, and it's very close to being able to replace tt++ for us (in addition to being awesome)! :)

**Comment by LiquidityC** [comment]
Happy to hear that you like it. Bombardment is fine. People tend to mud differently so there are different “must haves” for different people. These kinds of issues help me cover more bases. 😊
