### ISSUE TITLE
aggressively keeping the telnet session alive

### ISSUE THREAD

**Issue by robg204** [LiquidityC/Blightmud#59]
Last request I have, honest (and everything else works amazing to date):

Users who may have their client live in Azure will have an issue where any period of inactivity will lead to their session timing out in a weird way.  The client will remain responsive, but the mud will stop responding.  This is because of azure's session firewalls.

In tintin, we get around this by creating a timer (tick) that sends a keepalive (without unidling your character on the mud), with something like this:

#tick {keepalive} {#send \xFF\xF1\} {60};

These hex characters seem to be unliked by rlua as they come back into UTF8, but honestly, this is a bad way of fixing this anyway.  Can we have a world option to enable / set interval of keepalives on the telnet session?  ie: setKeepalive on the TcpStream?

**Comment by LiquidityC** [comment]
Seems doable. I’ll take a swing at it when I get some spare time. For now I think you can get your lua timer working by escaping your slashes. Eg. `\xFF` should be `\\xFF` in lua

**Comment by robg204** [comment]
> Seems doable. I’ll take a swing at it when I get some spare time. For now I think you can get your lua timer working by escaping your slashes. Eg. `\xFF` should be `\\xFF` in lua

I had tried that, unfortunately, \\xFF\\xF1 sends literally "\xFF\xF1" to the mud (like.. as if you just typed that at the prompt with nothing converting it to ), rather than the keepalive sequence.  It's possible there is a way to make it go, but I have yet to figure it out.  I'll keep poking at it, as well.  :)

**Comment by LiquidityC** [comment]
Ok. Then this amounts to two new features. One for keep alive and one for sending byte data from lua. 😊

**Comment by LiquidityC** [comment]
Come to think of it try concatenation good bytes with a string in lua. I’m no lua expert but it might work. 

`blight:send(“” .. 0xff .. 0xf1)`

It might not work. But it’s worth a shot

**Comment by robg204** [comment]
> Come to think of it try concatenation good bytes with a string in lua. I’m no lua expert but it might work.
> 
> `blight:send(“” .. 0xff .. 0xf1)`
> 
> It might not work. But it’s worth a shot

I actually had that thought as well, that just sends "255241" to the mud though.  I'll keep noodling around.  I had thought that set_keepalive(&self, time) had stabilized as part of std::net::TcpStream but apparently it hasn't, yet.  I think I must have been using it in nightly.

**Comment by robg204** [comment]
I also tried using string.char(0xff), unfortunately I get the same error as if I just did blight:send("\0xFF"):
callback error: error converting Lua string to &str (invalid utf-8 sequence of 1 bytes from index 0)

**Comment by LiquidityC** [comment]
Ok, I had to test this. I have a working implementation for `blight:send_bytes({ 0xff, 0xf1 })`.
I just need to write some helpfiles and confirm but my initial tests seem to work. Should be available on the dev branch before the weekend is over.

As for the keep alive function I'll check that out later. That might not be such a quick fix. We'll have to see.

**Comment by LiquidityC** [comment]
I've decided against hard coding any keep alive logic into blightmud. The tools are there if you want to build something on your own but I don't want lot's of scheduling and stuff ticking in the background. So I'm closing this.
