### ISSUE TITLE
Error running release build

### ISSUE THREAD

**Issue by ryanmichaelsmith** [LiquidityC/Blightmud#64]
**Describe the bug**
After building a release target of BlightMud, it immediately crashes. This is a brand new Ubuntu 18.04 LTS VM. It works fine with a debug target.

**To Reproduce**
I would assume that a brand new vm would have this issue, but perhaps there's something peculiar about my environment.

**What terminal are you using?**
Originally, openssh running in a tmux pane to another server. I then also tried using putty to connect directly.

**What mud were you playing?**
Host? 3kingdoms Port? 23 Website? http://www.3k.org  (not mud specific though, I haven't connected yet)

**Screenshots**
![image](https://user-images.githubusercontent.com/161915/85315746-9fa2fe80-b489-11ea-9eb4-5da782a717d5.png)

So  also have seen two error reports.
1st:
```
name = 'blightmud'
operating_system = 'unix:Ubuntu'
crate_version = '0.4.2'
explanation = '''
Panic occurred in file 'src/main.rs' at line 160
'''
cause = 'called `Result::unwrap()` on an `Err` value: Os { code: 25, kind: Other, message: "Inappropriate ioctl for device" }'
method = 'Panic'
backtrace = '''

   0: 0x56427bce2a43 - std::rt::lang_start::{{closure}}::h799748cf7108c9ba
   1: 0x56427bfebe78 - std::rt::lang_start_internal::{{closure}}::h44dc84346eeba462
                at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/rt.rs:52
                 - std::panicking::try::do_call::h3559ee6be71549e2
                at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panicking.rs:331
                 - std::panicking::try::h78f4c77016541848
                at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panicking.rs:274
                 - std::panic::catch_unwind::hfe46f382761b3d41
                at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panic.rs:394
                 - std::rt::lang_start_internal::he05790f0cb2000df
                at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/rt.rs:51
   2: 0x56427bc8e7b2 - main
   3: 0x7f8e5d414b97 - __libc_start_main
   4: 0x56427bc6131a - _start
   5:        0x0 - <unresolved>'''
```

And 2nd:
```
name = 'blightmud'
operating_system = 'unix:Ubuntu'
crate_version = '0.4.2'
explanation = '''
Panic occurred in file 'src/main.rs' at line 172
'''
cause = '[!!] Panic: No such file or directory (os error 2)'
method = 'Panic'
backtrace = '''

   0: 0x55650a587e78 - std::rt::lang_start_internal::{{closure}}::h44dc84346eeba462
                at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/rt.rs:52
                 - std::panicking::try::do_call::h3559ee6be71549e2
                at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panicking.rs:331
                 - std::panicking::try::h78f4c77016541848
                at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panicking.rs:274
                 - std::panic::catch_unwind::hfe46f382761b3d41
                at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panic.rs:394
                 - std::rt::lang_start_internal::he05790f0cb2000df
                at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/rt.rs:51
   1: 0x55650a22a7b2 - main
   2: 0x7f1df4796b97 - __libc_start_main
   3: 0x55650a1fd31a - _start
   4:        0x0 - <unresolved>'''
```

**Comment by ryanmichaelsmith** [comment]
I just tried building in Debian Buster running in WSL v2. Same error as the second one. Just to add a data point.

**Comment by LiquidityC** [comment]
Oh, great. Thanks for submitting a bugreport. The first error seems to be that blightmud is unable to determine your terminal size. Whatever setup you were using when this error occured seems to have problems with supplying the terminal size. Not sure I can do much about that.

The second error I'm looking into. Sadly the dump isn't giving me much to go on. I'd assume that blightmud fails to open a file.
Would you be able to confirm that you have the following dirs in your $HOME folder:
- `~/.local/share` and `~/.local/share/blightmud`
- `~/.config` and `~/.config/blightmud`

If any of those don't exist, in particular the root dirs `.config` and `.local` then I just pushed some code that ought to fix your problem.

**Comment by ryanmichaelsmith** [comment]
Good news. The new code did fix my problem. As you suspected, I did not have a .config folder in my home directory. The rest of the folders all existed.

The first issue went away before and is not reproducible at this time. I'm going to assume it was something wonky with my environment at the time.

Thank you, sir. I'll close this issue.
