### ISSUE TITLE
Support for binding keys

### ISSUE THREAD

**Issue by ryanmichaelsmith** [LiquidityC/Blightmud#66]
How about adding support to bind keys?

Something like: blight:add_macro(keyId, callback)

keyID would be a way to identify a key. Things like function keys, numpad, etc. Callback being the function that is called when the key is pressed. This would add even more value if there were also built-in methods for working with the input buffer, scrollback, etc. Because you'd have user-defineable hotkeys.

**Comment by LiquidityC** [comment]
Yes definitely. It might be tricky due to how the underlying terminal library works. But I’ll take a swing at it. Because I agree that it would be nice.

**Comment by LiquidityC** [comment]
Ok, so I totally got this working in a pleasant way. You'll be able to bind `Ctrl-(a-z0-9)`, `Alt-(a-z0-9)` and `F1-12`. I'll merge once the tests on the PR pass. I won't release it at once but I'm counting on some testing from whoever wants to try it out during the week. Then I'll create an actual release (0.5 probably) before the weekend.

But as I mentioned, testing would be great. You can just build from the dev branch to test it out in a few minutes.
