### ISSUE TITLE
Silent Lua errors

### ISSUE THREAD

**Issue by Xandaros** [LiquidityC/Blightmud#75]
At least in some cases, Lua errors are silently ignored. For example, in a GMCP callback:
```lua
blight:on_gmcp_ready(function()
    blight:register_gmcp("Char")
    blight:add_gmcp_receiver("Char.Vitals", function(data)
        nonexistent()
    end)
end)
```
Nothing in the output, no report in `/tmp` and no mention of it in `~/.local/share/blightmud/logs/log.txt`. The execution of the hook does get aborted, though.

**Comment by LiquidityC** [comment]
Thanks for the report and excellent example.
