### ISSUE TITLE
Split window

### ISSUE THREAD

**Issue by Xandaros** [LiquidityC/Blightmud#80]
Something I have always wanted in a MUD client is the ability to have multiple windows up at once in a vim-like fashion.

That way you could have, for example, one main window, a window displaying a map, a window showing channel chatter, etc.

I suggest adding a function for creating windows. Perhaps `blight:add_window()`.

I'm not entirely sure how you would actually output to a different window, though. `blight:output` could take an index as first parameter, but it breaks existing scripts and would be less convenient to use for single-window users.
Maybe a second output function, something like `blight:output_window(number, string...)`?

Finally, there should be an option to resize windows. Capturing mouse events would probably be the most convenient for the user, but that's not entirely necessary for now. Just having functions that resize should be fine.

The main question remaining is how to lay out the windows. I would like a master+stack layout so you have one main window on the left and a column of windows on the right. How the windows are laid out is a choice that should be given to the user, though, and I'm not entirely sure what the best way to do that would be.
One option:
Have a concept of a window group.
There is one main window group, which will be laid out over the entire screen.
A window group can contain windows and other window groups.
A window group can either be horizontal or vertical.

That would essentially be how the window manager i3 (and probably others) does its layout. Another option is using predefined layouts, like, for example, Xmonad handles it.

I'm leaning towards manual. Should be easier to implement and unlike a window manager, I expect the number of windows to remain fairly static throughout a session.

Thoughts? I hope this doesn't go against some design philosophy :smile:

**Comment by Xandaros** [comment]
Possible, concrete API:

`blight:create_window() -> userdata<Window>` - Creates a new Window, but does not display it or anything
`blight:get_main_window() -> userdata<Window>` - Returns the main window
`blight:set_layout(table)` - Sets the layout. The table contains windows or tables at numerical indices. There is also a key `vertical`, which, when truthy, makes the layout vertical instead of horizontal. Subtables follow the same format. If the main window is not part of the layout, it is assumed to be in the first position.

`Window:clear()` - Clears the contents of a window
`Window:output(string...)` - Like `blight:output`, but outputs to the window
`Window:set_size(integer)` - Sets the size of the window in characters. If the size is larger than fits on the screen or the size would cause other windows to go off-screen, the size is ignored. Whether the size is width or height is determined by whether the layout is horizontal or vertical.
`Window:reset_size()` - Resets size. Same as `Window:set_size(nil)`. Windows without size are evenly sized.
`Window:scroll(integer)` - Scroll down N rows. (scroll up if N is negative)
`Window:delete()` - Deletes the window. Same as letting the window get garbage collected. The main window is never deleted.
`Window:activate()` - Marks the window as the active window. Normal scrolling with PgUp and PgDown always affects the active window. The default active window is the main window.

Note that this allows you to remove a window from the layout, (or never place it in the layout in the first place) but not lose its contents and still output to it.

What do you think? I'm not entirely sold on the size handling, but it seems reasonable to me so far. Existing scripts will also continue to work.

**Comment by LiquidityC** [comment]
This would require a rather massive overhaul of the back end ui code and was never an intended path I had in mind for the project. The idea isn't bad but I doubt it will ever become a priority for me. There are larger more gui oriented mud alternatives that offer these kinds of solutions.

**Comment by Xandaros** [comment]
I had a look at the UI code before posting this and it honestly doesn't look like it would be a lot.

If you don't have anything against the idea as such, I might take a look at adding it myself. And yes, there are clients that do this, but they tend to run in a window. I much prefer terminal clients and of the ones I have used so far, none really offered this to a satisfying degree.
Tintin allows vertical splits only, for example. It also has a disgusting scripting language, which made me very glad to have found yours :smile:

**Comment by LiquidityC** [comment]
No problem. If you build something functional I will merge it. No problem. It's not something that I'm able to prioritize myself right now but that doesn't mean it can't be done :wink: 

I never got along with tintin++ script either. That's why I decided to start this project.
