### ISSUE TITLE
Ability to poll trigger list, alias list, timer list

### ISSUE THREAD

**Issue by robg204** [LiquidityC/Blightmud#90]
Discussed on discord:

Currently, we track aliases, timers, and triggers (I do this in tables), so that we may remove triggers when reloading in place, or for other reasons.  It would be nice to be able to poll the client for a list of active IDs from lua rather than having to track it ourselves.  Useful for situations where we think our environment is wrong.

**Comment by LiquidityC** [comment]
This information is actually hidden in the lua state already. Triggers and aliases are stored in tables. So it should be pretty easy to implement on the lua side. Check `lua_script.rs` for the names of those tables.

**Comment by robg204** [comment]
Today I learned.. :)  Great! Thanks!

**Comment by LiquidityC** [comment]
I think we could still write some more user friendly wrappers for it.

**Comment by LiquidityC** [comment]
I've decided I want to extend the new functionality slightly by returning a table containing `id` as key and a string representation of the `regex` as value where applicable. That should make the information slightly more useful when debugging and what not.

I'll also create some macros based on this such as `/aliases` and `/triggers`

**Comment by LiquidityC** [comment]
This is done now, I extended the following:
- `blight:get_aliases()` and `blight:get_triggers()` returns proper ids and objects in a table
- Added macros `/aliases` and `/triggers`
- Added methods `blight:enable_alias(int, bool)` and `blight:enable_trigger(int, bool)`
- Relevant documentation and tests
