### ISSUE TITLE
/load (and blight:load) don't parse paths starting with ~

### ISSUE THREAD

**Issue by robg204** [LiquidityC/Blightmud#98]
~ paths like ~/mud/script.lua dont work in /load and blight:load, and yield no such file or directory (os err 2).

**Comment by LiquidityC** [comment]
This isn't really a bug. Expanding ~ and environment variables such as $HOME etc. id known as 'shell expansions' it's generally a feature within the shell. It's not a default feature in any application.

We could implement it. There's a nifty crate called [shellexpand](https://crates.io/crates/shellexpand) which would solve this with probably very little code required.
